name: Open release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

#
# TODO
# - Add tags for each app (e.g. search@3.0.1) for easier parsing
# - Print versions name to commit, for easier Vercel deployments
#
jobs:
  release:
    name: Prepare release with Changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4 # Use version from package.json
      - name: Setup Node.js 16 # It was default for Changesets action, check if it can be bumped to v18
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        name: Install pnpm
      - run: pnpm install
        # TODO -> publish to npm as pre-release https://github.com/changesets/changesets/blob/8447c677a37d1d23858059e0ce2b5cd98f4c24ae/docs/snapshot-releases.md
      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          title: Release to npm
          commit: Release to npm
          publish: pnpm publish
          # action is automatically pushing even before PR is merged?
          # This should:
          # 1. Push to "next" every time
          # 2. Push to latest AFTER PR is merged
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push tags
        run: npx changeset tag && git push --follow-tags